import {
  CellSpanModule,
  CellStyleModule,
  ClientSideRowModelModule,
  ColumnAutoSizeModule,
  EventApiModule,
  LocaleModule,
  ModuleRegistry,
  NumberEditorModule,
  NumberFilterModule,
  PaginationModule,
  RowApiModule,
  RowAutoHeightModule,
  RowSelectionModule,
  RowStyleModule,
  TextEditorModule,
  TextFilterModule,
  UndoRedoEditModule,
  ValidationModule,
  CustomEditorModule,
} from 'ag-grid-community';
import { ColumnsToolPanelModule, SetFilterModule } from 'ag-grid-enterprise';

ModuleRegistry.registerModules([
  ColumnAutoSizeModule,
  CellStyleModule,
  CellSpanModule,
  EventApiModule,
  NumberEditorModule,
  PaginationModule,
  RowSelectionModule,
  RowStyleModule,
  TextEditorModule,
  TextFilterModule,
  ValidationModule,
  NumberFilterModule,
  LocaleModule,
  ClientSideRowModelModule,
  UndoRedoEditModule,
  SetFilterModule,
  ColumnsToolPanelModule,
  RowAutoHeightModule,
  RowApiModule,
  CustomEditorModule,
]);
